#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: LEDE Update Checker

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Get Commit Hash
      id: getHash
      run: |
        commit_hash=$(git ls-remote "$REPO_URL" "refs/heads/$REPO_BRANCH" | awk '{print $1}')
        echo "commitHash=$commit_hash" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3
      with:
        path: .lede_commitHash
        key: commitHash_${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .lede_commitHash

    - name: Commit and push changes
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .lede_commitHash
        git commit -m "Update LEDE commit hash: ${{ steps.getHash.outputs.commitHash }}"
        git push

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: LEDE_Update
        client-payload: |
          {
            "repository_owner": "coolsnowwolf",
            "repository_name": "lede",
            "repository_branch": "master"
          }

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 5
        workflow_id: ${{ github.workflow }}
